# Generated by Django 4.2.2 on 2024-02-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
