# Generated by Django 4.2.2 on 2024-02-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
