# Generated by Django 4.2.2 on 2024-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('num_family_members', models.IntegerField()),
                ('aadhar_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
