# Generated by Django 4.2.2 on 2024-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_formdata_delete_contact_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='serial_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='unique_id',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
