# Generated by Django 4.2.2 on 2024-02-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_formdata_serial_no_formdata_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='name',
        ),
        migrations.AddField(
            model_name='formdata',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
