# Generated by Django 4.2.2 on 2024-02-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_state_formdata_taluka'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='Type_of_members',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
