# Generated by Django 4.2.2 on 2024-02-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_formdata_aadhar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
