# Generated by Django 4.2.2 on 2024-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_formdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
            ],
        ),
    ]
