# Generated by Django 4.2.2 on 2024-02-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_allimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allimages',
            name='image',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
