# Generated by Django 4.2.2 on 2024-02-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_allimages_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllImages',
        ),
    ]
